config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "posts#index"
  resources :posts do
    member do
      patch '/publish', to: 'posts#publish'
      patch '/unpublish', to: 'posts#unpublish'
    end
    collection do
      get '/tagged/:tag', to: 'posts#tagged'
    end
    resources :comments, only: :create
  end
  resources :comments, only: :destroy
  get 'dashboard', to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :name, presence: true
  validates :content, presence: true

  default_scope { order(:created_at) }
end

app/models/post.rb
class Post < ApplicationRecord
  enum is_published: [:unpublished, :published, :scheduled]
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :photo, dependent: :destroy

  after_initialize :set_publish_date

  validates :title, presence: true
  validates :content, presence: true
  validates :publish_date, presence: true
  validate :publish_date_and_published

  default_scope { order(publish_date: :desc) }

  acts_as_taggable_on :tags

  self.per_page = 10

  def self.search(query)
    Post.where(['content iLIKE :query OR title iLIKE :query', query: "%#{query}%"])
  end

  def stripped_content
    ActionView::Base.full_sanitizer.sanitize(content)
  end

  def self.publish_scheduled_posts
    Post.scheduled.where('publish_date <= ?', Time.now).each(&:published!)
  end

  private

  def publish_date_and_published
    if published? && publish_date > Time.now
      errors.add(
        :publish_date,
        "Can't be in the future if 'is_published' is checked. Posts will automatically be published if set in the future."
      )
    end
  end

  def set_publish_date
    self.publish_date ||= Time.now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    authorize @comment
    if @comment.save
      redirect_to post_path(@comment.post, anchor: "comment-#{@comment.id}")
    else
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :content)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_after_action :verify_policy_scoped

  def index
    users_posts = PostPolicy::Scope.new(current_user, Post).resolve_dashboard
    @published_posts = users_posts.published
    @unpublished_posts = users_posts.unpublished
    @scheduled_posts = users_posts.scheduled
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy, :publish, :unpublish]
  before_action :set_tags, only: [:new, :edit, :create, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:q]
      @posts = policy_scope(Post).search(params[:q]).paginate(:page => params[:page])
    else
      @posts = policy_scope(Post).paginate(:page => params[:page])
    end
    @posts = @posts.tagged_with(params[:tag].split(' '), any: true) if params[:tag]
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post
    if @post.save
      redirect_to edit_post_path(@post)
    else
      render :new
    end
  end

  def edit
    authorize @post
  end

  def update
    remove_attachment if params[:other] && params[:other][:remove_attachment] == "1"
    authorize @post
    if @post.update(post_params)
      redirect_to edit_post_path(@post)
    else
      render :edit
    end
  end

  def show
    authorize @post
    @comment = Comment.new
  end

  def destroy
    @post.destroy
    authorize @post
    flash[:notice] = "Post entitled '#{@post.title}' has been deleted."
    redirect_to dashboard_path
  end

  def publish
    authorize @post
    @post.publish_date = Time.now
    @post.published!
    @post.save
    redirect_to post_path(@post)
  end

  def unpublish
    authorize @post
    @post.unpublished!
    @post.save
    redirect_to post_path(@post)
  end

  private

  def remove_attachment
    @post.photo.purge
  end

  def set_tags
    @tags = ActsAsTaggableOn::Tag.all.map(&:name)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
      :title,
      :is_published,
      :publish_date,
      :content,
      :photo,
      tag_list: []
    )
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dashboard/_post_list.html.erb
<ul class="list-group list-group-flush">
<% posts.each do |post| %>
  <li class="list-group-item d-flex align-items-center">
    <span>
      <div><strong><%= link_to post.title, post_path(post) %></strong></div>
      <span class="small mr-1">
        <%= post.publish_date.strftime('%Y-%m-%d') %>
      </span>
      |
      <span class="small ml-1">
        <%= pluralize(post.comments.count, 'comment') %>
      </span>
    </span>
    <span class="ml-auto">
      <%= link_to 'Edit', edit_post_path(post), class: "badge badge-secondary" %>
      <% if published %>
        <%= link_to 'Unpublish', unpublish_post_path(post), method: :patch, class: "badge badge-primary" %>
      <% else %>
        <%= link_to 'Publish', publish_post_path(post), method: :patch, class: "badge badge-primary" %>
      <% end %>
      <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure?" }, class: "badge badge-danger" %>
    </span>
  </li>
<% end %>
</ul>

app/views/dashboard/index.html.erb
<div class="row mb-5">
  <div class="col">
    <h1>Your posts</h1>
  </div>
</div>


<div class="row mb-5">
  <div class="col">
    <h2>Published posts</h2>
    <%= render 'post_list', posts: @published_posts, published: true %>
  </div>
</div>

<div class="row mb-5">
  <div class="col">
    <h2>Unpublished posts</h2>
    <%= render 'post_list', posts: @unpublished_posts, published: false %>
  </div>
</div>

<div class="row mb-5">
  <div class="col">
    <h2>Unpublished posts</h2>
    <%= render 'post_list', posts: @scheduled_posts, published: false %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= tinymce_assets %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container py-5">
      <% if notice %>
        <div class="alert alert-info"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post_form.html.erb
<%= simple_form_for(post) do |f| %>
    <%= f.input :title %>
    <%= f.input :is_published, collection: Post.is_publisheds.keys, as: :radio_buttons %>
    <%= f.input :publish_date, as: :string, input_html: { id: 'publish_date_picker' },
      hint: 'If you set the publish date to the future, your post will automatically be published at that time.'
    %>
    <%= f.input :tag_list, collection: @tags, input_html: { id: 'tag_picker', multiple: true }, hint: 'You can pick multiple tags' %>
    <% if post.photo.attached? %>
      <%= simple_fields_for :other do |o| %>
        <%= image_tag post.photo %>
        <%= o.input :remove_attachment, as: :boolean, label: "Remove current attachment?" %>
      <% end %>
    <% else %>
      <%= f.input :photo, label: "Featured image (optional)", hint: 'This image appears at the top of the post' %>
    <% end %>
    <%= f.text_area :content, :class => "tinymce", :rows => 15, :cols => 120 %>
    <% if post.new_record? %>
      <%= f.submit 'Create Post', class: "btn btn-primary mt-2" %>
    <% else %>
      <%= f.submit 'Save Post', class: "btn btn-primary mt-2" %>
    <% end %>
<% end %>

app/views/posts/_tag_list.html.erb
<% tags.each do |tag| %>
  <span class="badge badge-pill badge-info"><%= tag %></span>
<% end %>

app/views/posts/_unpublished_notice.html.erb
<% unless @post.published? %>
  <div class="alert alert-info">
    You are viewing <%= @post.scheduled? ? "a post scheduled for #{@post.publish_date}." : "an unpublished post." %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'post_form', post: @post %>
<% view_post_text = @post.published? ? 'View Post' : 'Preview Post' %>
<%= link_to view_post_text, post_path(@post), class: 'mt-3 btn btn-secondary' %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render 'shared/sidebar' %>
  </div>
  <div class="col-12 col-md-9">
    <% if @posts.empty? %>
      <div class="alert alert-secondary">
        No posts found.
      </div>
    <% else %>
      <% @posts.each do |post| %>
        <div class="card post_box mb-5 relative">
          <% if post.photo.attached? %>
            <%= image_tag post.photo, alt: post.title, class: 'card-img-top' %>
          <% end %>
          <div class="card-body">
            <h2><%= post.title %></h2>
            <div class="mb-2"><%= truncate(post.stripped_content, length: 100, omission: '... (continued)') %></div>
            <div class="d-flex justify-content-between align-items-center">
              <span class="small"><%= post.publish_date.strftime('%Y-%m-%d') %></span>
              <span><%= render 'posts/tag_list', tags: post.tags %></span>
            </div>
          </div>
          <%= link_to "", post_path(post), class: "full-link" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="col text-center">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'post_form', post: @post %>

app/views/posts/show.html.erb
<div class="row mb-5">
  <div class="col">
    <%= render 'posts/unpublished_notice', post: @post %>
    <% if @post.photo.attached? %>
      <%= image_tag @post.photo, alt: @post.title, class: 'featured-img mb-3 rounded' %>
    <% end %>
    <h1><%= @post.title %></h1>
    <% if policy(@post).edit? %>
      <div class="mb-3">
        <%= render 'shared/post_controls', post: @post %>
      </div>
    <% end %>
    <div class="d-flex align-items-center justify-content-between">
      <span>
        <strong>Posted on:</strong> <%= @post.publish_date.strftime('%Y-%m-%d') %>
        <span class="ml-3"><strong>Posted by:</strong> <%= @post.user.username %></span>
      </span>
      <span class="ml-3">
        <%= render 'posts/tag_list', tags: @post.tags %>
      </span>
    </div>
    <article class="mt-5">
      <%= @post.content.html_safe %>
    </article>
  </div>

</div>


<div class="row">
  <div class="col-12 mb-3">
    <h2>Comments</h2>
  </div>
  <% if @post.comments.empty? %>
    <div class="col-12 col-md-8">
      <div class="alert alert-secondary">
        There are no comments yet.
      </div>
    </div>
  <% else %>
    <div class="col-12 col-md-8">
      <%= render 'shared/comment_list', comments: @post.comments %>
    </div>
  <% end %>
  <% if @post.published? %>
    <div class="col">
      <%= simple_form_for([@post, @comment], remote: true) do |f| %>
        <%= f.input :name %>
        <%= f.input :content %>
        <%= f.submit "Post comment", class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_comment_list.html.erb
<% comments.each do |comment| %>
  <div class="comment" id="comment-<%= @comment.id %>">
    <div class="d-flex justify-content-between mb-3">
      <strong><%= comment.name %></strong>
      <span><%= comment.created_at.strftime('%Y-%m-%d') %></span>
    </div>
    <p><%= comment.content %></p>
    <% if policy(comment).destroy? %>
      <%= link_to 'Delete', comment_path(comment), method: :delete, class: 'badge badge-pill badge-danger' %>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Blog!', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <span class="navbar-text" id="username"><%= current_user.username %></span>
        <li class="nav-item"><%= link_to 'New post', new_post_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: 'nav-link'  %></li>
        <li class="nav-item"><%= link_to 'Register', new_user_registration_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
    <%= render 'shared/search_form' %>
  </div>
</nav>

app/views/shared/_post_controls.html.erb
<%= link_to "Edit", edit_post_path(post), class: "badge badge-secondary" %>
<% if @post.published? %>
  <%= link_to 'Unpublish', unpublish_post_path(@post), method: :patch, class: 'badge badge-info' %>
<% else %>
  <%= link_to 'Publish', publish_post_path(@post), method: :patch, class: 'badge badge-info' %>
<% end %>
<%= link_to "Delete", post_path(post), method: :delete, class: "badge badge-danger"  %>

app/views/shared/_search_form.html.erb
<%= simple_form_for :search, url: posts_path, html: { class: 'form-inline my-2 my-lg-0' }, method: :get do |f| %>
  <%= f.input :q, input_html: { name: 'q', id: 'search-bar', placeholder: 'Search', class: ' mr-sm-2' }, label: false %>
  <%= f.submit "Search", name: nil, class: 'btn btn-outline-success my-2 my-sm-0' %>
<% end %>

app/views/shared/_sidebar.html.erb
<h3>Posts by Tag</h3>
<% if ActsAsTaggableOn::Tag.any? %>
<ul class="list-group list-group-flush">
  <% Post.published.tag_counts_on(:tags).order(:name).each do |tag| %>
  <li class="list-group-item d-flex justify-content-between align-items-center relative">
    <%= tag.name %>
    <span class="badge badge-secondary badge-pill"><%= Post.published.tagged_with(tag).count %></span>
    <%= link_to "", posts_path(tag: tag.name), class: "full-link"  %>
  </li>
  <% end %>
</ul>
<% else %>
  <div class="alert alert-light">There are no tagged posts yet.</div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-secondary mt-3" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-secondary mt-3"  %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>